//get request to access users
GET http://localhost:3000/users

###

//post request to register new user with username and password in json
POST http://localhost:3000/users/register
Content-Type: application/json

{
"UserName": "befi",
"Password": "password123",
"FirstName":"bef",
"LastName":"iwar",
"Email":"befiwar458@mannawo.com"
}



###

//post request to login with username and password in json
POST http://localhost:3000/users/login
Content-Type: application/json

{
"UserName": "DammyTheSLayer",
"Password": "password6266"
}

###

//post request to login with username and password in json
POST http://localhost:3000/users/login
Content-Type: application/json

{
"UserName": "Roshan",
"Password": "password666"
}


###

//post request to forgetpassword with username or email in json
POST http://localhost:3000/users/forgetPassword
Content-Type: application/json

{
"UserNameorEmail": "befiwar458@mannawo.com"
}


###
//post request to reset password , paste the link that you get via email
POST http://localhost:3000/users/resetPassword/61f55041f83ee12b737d6aaa/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkRhbW15VGhlU0xheWVyIiwidXNlckVtYWlsIjoiRGFtbXlUaGVTTGF5ZXIiLCJpYXQiOjE2NDM0NjY4NzIsImV4cCI6MTY0MzQ2Nzc3Mn0.J66ve0nujySDi1qqXzpEgLUaX_eGTKT0pGetVmrxcwc
Content-Type: application/json

{
"Password": "password6266"
}
