//get request to access users
GET http://localhost:8080/users

###

//post request to register new user with username and password in json
POST http://localhost:8080/users/register
Content-Type: application/json

{

"UserName": "befi",
"Password": "password123",
"FirstName":"bef",
"LastName":"iwar",
"Email":"befiwar458@mannawo.com"
}



###

//post request to login with username and password in json
POST http://localhost:3000/users/login
Content-Type: application/json

{
"UserName": "DammyTheSLayer",
"Password": "password6266"
}

###

//post request to login with username and password in json
POST http://localhost:8080/users/login
Content-Type: application/json

{
"UserName": "Roshan",
"Password": "password666"
}


###

//post request to forgetpassword with username or email in json
POST http://localhost:8080/users/forgetPassword
Content-Type: application/json

{
"UserNameorEmail": "befiwar458@mannawo.com"
}


###
//post request to reset password , paste the link that you get via email
POST http://localhost:3000/users/resetPassword/61f55041f83ee12b737d6aaa/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkRhbW15VGhlU0xheWVyIiwidXNlckVtYWlsIjoiRGFtbXlUaGVTTGF5ZXIiLCJpYXQiOjE2NDM0NjY4NzIsImV4cCI6MTY0MzQ2Nzc3Mn0.J66ve0nujySDi1qqXzpEgLUaX_eGTKT0pGetVmrxcwc
Content-Type: application/json

{
"Password": "password6266"
}


###

GET http://localhost:8080/users 
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjBiMDcxMzA0ZjllNTRjY2VhZDA5ZGEiLCJpYXQiOjE2NDQ4OTg0NzZ9.I3HFyhgl0huiOGWJEg0Kgc0F7VfMGFibH-tAOCsGrU0

//post request to save a new emergency support option to database 
POST http://localhost:8080/emergency/create
Content-Type: application/json

{
"name": "AccessAbility Supports",
"type": "Financial Assistance",
"phone":"1-866-594-3777",
"email": "deptsdh@gov.pe.ca ",
"address":"no address",
"description": "Our government wants to ensure Islanders living with disabilities can access the tools they need to reach their full potential and contribute to society as fully as possible. These improvements mean supports will be more personalized and focus on empowering individuals and their families.Supports include:"
}




###
//get request to access list of emergencies
GET http://localhost:8080/emergency/list


### 
//update personal information edit profile
PATCH http://localhost:8080/users/edit/personalinfo
Content-Type: application/json

{
"userFirstName": "Roshan",
"userMiddleName": "Jyanesh",
"userLastName": "seeam",
"userDOB": "1999-09-23"
}
