//get request to access users
GET http://localhost:3000/users

###

//post request to register new user with username and password in json
POST http://localhost:3000/users/register
Content-Type: application/json

{
"UserName": "tec",
"Password": "password12345",
"FirstName":"tec",
"LastName":"cofa",
"Email":"tecofa8007@nahetech.com"
}



###

//post request to login with username and password in json
POST http://localhost:3000/users/login
Content-Type: application/json

{
"UserName": "tec",
"Password": "password12345"
}

###

//post request to login with username and password in json
POST http://localhost:3000/users/login
Content-Type: application/json

{
"UserName": "Roshan",
"Password": "password666"
}


###

//post request to forgetpassword with username or email in json
POST http://localhost:3000/users/forgetPassword
Content-Type: application/json

{
"UserNameorEmail": "tec"
}


###
//post request to reset password , paste the link that you get via email
POST (paste link here)
Content-Type: application/json

{
"Password": "password6266"
}
